services:
  weather-frontend:
    image: boulundeasv/cd-weather-web:prod
  
  weather-api:
    image: boulundeasv/cd-weather-api:prod
  
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
    labels:
      - "com.centurylinklabs.watchtower.enable=false"