services:
  weather-frontend:
    build:
      context: src
      dockerfile: WeatherFrontend/Dockerfile
    ports:
      - "5001:8080"
    depends_on: 
      - weather-api
  
  weather-api:
    build:
      context: src
      dockerfile: WeatherAPI/Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: forecasts
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
